os: linux
language: python
cache: pip
env: PYTHON=python
jobs:
    include:
        # Linux
        - python: 2.7
        - python: 3.8
        # macOS
        - os: osx
          language: generic
          env: PYTHON=python2.7
        - os: osx
          language: generic
         env: PYTHON=python3.8
install:
    - $PYTHON -m pip install --upgrade pip setuptools
    - $PYTHON -m pip install --upgrade coveralls flake8 mock psutil pyopenssl pysendfile six
script:
    - ./.ci/travis/run.sh
after_success:
    - |
        if [[ $TRAVIS_PYTHON_VERSION == '3.8' ]] && [[ "$(uname -s)" != 'Darwin' ]]; then
            echo "sending test coverage results to coveralls.io"
            coveralls
        fi
