os: linux
language: python
cache: pip
env: PYTHON=python
jobs:
    include:
        # Linux
        - python: 2.7
        - python: 3.8
        # macOS
        - os: osx
          osx_image: xcode11.3
          language: generic
          env: PYTHON=python2.7
        - os: osx
          osx_image: xcode11.3
          language: generic
          env: PYTHON=python3.7
install:
    - $PYTHON -m pip install --upgrade pip setuptools
    - $PYTHON -m pip install --upgrade coveralls flake8 mock psutil pyopenssl pysendfile pytest six
script:
    - $PYTHON setup.py install
    - pytest .
    - $PYTHON pyftpdlib/test/runner.py || true
    - |
        if [[ "$TRAVIS_OS_NAME" == 'linux' ]]; then
            flake8 --ignore=E741,F841,W504
        fi
after_success:
    - |
        if [[ "$TRAVIS_PYTHON_VERSION" == '3.8' ]]; then
            echo "sending test coverage results to coveralls.io"
            coveralls
        fi
